NOT-1028: Upgrade to storybook 6, fix CI job and fix/update most tests to code changes
beyondessential/tamanu pull request #3450
Opened 2023-01-26 03:13 UTC by dannash100

### Changes
Upgrades and fixes storybook without any other changes to babel between desktop and shared-src.
Quite alot of breaking changes in that major version to v6 see the restructure of all the config boilerplate

- Upgrade to v6
- Utilize webpack5 builder and manager
- Various fixes for the load of errors in CI step `storybook-verify`
- Utilize new addon for controls ( example in Button )
- Fix a tonne of stories as they are from days of connect Redux HOC and needed to be reworked due to patterns of datafetching and state management changes.

<img width="1407" alt="Screen Shot 2023-01-26 at 4 06 35 PM" src="https://user-images.githubusercontent.com/38335330/214750342-b41f5425-86e8-4e1d-835b-c699f1c05054.png">

With controls addon which i enabled for buttons as example
<img width="1101" alt="Screen Shot 2023-01-27 at 10 08 24 AM" src="https://user-images.githubusercontent.com/38335330/214950916-03df2c89-a56b-4363-b453-067d7d33e81e.png">

### Checklist

- [x] Code is finished

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/pulls?q=is%3Apr+is%3Aopen+release+in%3Atitle))
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

2023-01-26 03:35 UTC, tcaiger approved these changes
The changes look good to me and are contained to desktop storybook so should be safe I reckon

2023-01-26 03:57 UTC, mcccclean requested changes
LGTM generally but it seems like the fix isn't quite enough to get the CI side of things over the line - change request to switch that back off before merging just to avoid misleading :x:'s on dev.

2023-02-02 21:58 UTC, mcccclean approved these changes

2023-02-13 02:23 UTC, mcccclean requested changes
Worried that we're papering over a couple things that we don't actually want to ignore; just worth one more pass to see if these're properly fixable first.

2023-02-15 22:00 UTC, mcccclean approved these changes

2023-02-19 21:22 UTC, merged