SAV-139 + SAV-140: Allow configuring filters in manually emailed COVID-19 clearance certificate
beyondessential/tamanu pull request #3628
Opened 2023-03-01 03:55 UTC by chris-bes

### Changes
**Problem**: At the moment, all the configured filters (daysSinceSampleTime, labTestTypes, etc...) are only applied to automated covid clearance certificate, but not when manually emailed the certificate (by hitting send email in the Covid Clearance Cert modal)

**Fix**: I've moved all the configured filters into Settings table so that it can be used in both central and facility. And apply those filters to the manual emailed certificate

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/pulls?q=is%3Apr+is%3Aopen+release+in%3Atitle))
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

2023-03-01 21:11 UTC, EMcQ-BES submitted a review, later dismissed
Needs a code owner review

Code looks good to me, could we merge this to `dev` instead of `staging` though? Currently plan is to do one final dev to staging merge to avoid too much branch juggling.

2023-03-01 21:20 UTC, EMcQ-BES requested changes
Fix up tests plz

2023-03-02 01:03 UTC, EMcQ-BES approved these changes

2023-03-02 01:07 UTC, nick-beyondessential approved these changes

2023-03-02 01:09 UTC, merged