WAITM-605: Fix IdleDetectionLayer interaction with login status and add connection status updates to refresh endpoint
beyondessential/tamanu pull request #3648
Opened 2023-03-02 23:57 UTC by dannash100

### Changes

Auto logout tweaks from testing:
To address:

1. It was identified that idle logout timer was not re-initalizing on logout -> log back in. In an expected way. 
2. When sending post request on postman to login to central server without deviceId it returned a verbose and unideal error.
3. Sync disconnection alert was not following a predictable pattern due to some missing central server connection status changes.

- Idle detector conditionally added to component tree on loggedIn change
- Restore sync connection status to connected removed in final merge somehow
- Throw error early on no deviceId on sync login

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/pulls?q=is%3Apr+is%3Aopen+release+in%3Atitle))
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

2023-03-06 03:42 UTC, mcccclean requested changes
Just one little change please :pray:

2023-03-06 22:18 UTC, chris-bes approved these changes
Code owner stamp

2023-03-06 22:32 UTC, mcccclean requested changes

2023-03-07 00:40 UTC, mcccclean requested changes
LGTM, just one weird little bit to clean up.

Am I right in understanding that the whole point of the emitter/centralServerStatusChange  structure was to keep the redux store in sync with it, and that if we just look at the server connection directly the whole thing can be dropped entirely? What a good find :pray:

2023-03-07 00:46 UTC, mcccclean approved these changes

2023-03-07 01:39 UTC, merged