WAITM-601: Mobile logout from inactivity text spacing tweak
beyondessential/tamanu pull request #3699
Opened 2023-03-09 20:41 UTC by dannash100

### Changes
- Fix spacing on logout from inactivity so it doesn't push other elements down

![Screenshot_20230310_091521_Tamanu Mobile](https://user-images.githubusercontent.com/38335330/224151723-c26f4593-ff7f-45c3-88de-f8fb0ac1f2a5.jpg)

### Checklist

- [x] Code is finished
- [x] Tests are written
- [x] UI Screenshots added to the Linear issue
- [n/a] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/pulls?q=is%3Apr+is%3Aopen+label%3Arelease), or if the previous PR is merging into master then create a new release candidate PR for the next version following [the Slab doc](https://beyond-essential.slab.com/posts/merging-a-tamanu-ticket-okxp8s4s#h0y52-creating-a-release-candidate-pr))
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

2023-03-09 20:48 UTC, tcodling approved these changes
sweet pr as per usual

2023-03-09 21:09 UTC, mcccclean requested changes
Whew, beast of a PR - I do have some notes though, hopefully this doesn't result in too much of a rewrite...!!!

2023-03-09 21:16 UTC, mcccclean requested changes
Oh, wait, actually, jokes aside... I realised I DO have a note about the approach in this PR! It kind of kicks the can down the road a little bit, where if we change the text (for eg via translation) or use the display to show a different error message, this bug will return.

Rather than have the element appear/disappear and have the other elements adjust their margins to account for it, I think it'd be more of a robust solution to display the error message inside a fixed-height container which is always there. That way we don't need to do any calculation of individual heights of elements, and the "eHealth patient record" section doesn't need to be aware of whether we're showing an error message above it.

2023-03-13 22:05 UTC, mcccclean approved these changes

2023-03-13 22:27 UTC, merged