NASS-678: Clear select, autocomplete and search fields
beyondessential/tamanu pull request #3892
Opened 2023-04-11 00:51 UTC by tcodling

### Changes

This card adds a handy 'x' that can be used to clear the 3 following fields when a value is in them:
- Select
- Autocomplete
- Search

These three fields will now show up with an 'x' that will clear the input when clicked. In order to fit with Felicity's design I have added a custom "x" icon and also a custom "⌄" icon. (the material ui size ratio did not work with the design) 

### Checklist

- [x] Code is finished
- [x] UI Screenshots added to the Linear issue
- [x] Testing notes added to the Linear issue

_Upon merging:_

- [x] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/pulls?q=is%3Apr+is%3Aopen+label%3Arelease), or if the previous PR is merging into master then create a new release candidate PR for the next version following [the Slab doc](https://beyond-essential.slab.com/posts/merging-a-tamanu-ticket-okxp8s4s#h0y52-creating-a-release-candidate-pr))
  - [x] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)

2023-04-18 00:24 UTC, mcccclean requested changes

2023-04-20 06:31 UTC, mcccclean requested changes

2023-05-07 23:17 UTC, mcccclean requested changes
Almost there!

2023-05-07 23:20 UTC, mcccclean requested changes
Oops missed this one:

2023-05-08 00:55 UTC, dannash100 approved these changes
Thomas has done the requested changes - and there is a time pressure to get this merged today - not entirely sure if this will work - but Ill do the stamp having confirmed the changes 🙏  @mcccclean

2023-05-09 02:21 UTC, mcccclean approved these changes

2023-05-09 02:40 UTC, merged