NASS-796: Add table autorefresh
beyondessential/tamanu pull request #4291
Opened 2023-06-26 04:07 UTC by tcodling

### Changes

For the imaging and lab request tables in the sidebar, we want to add functionality that allows the page to refresh every 5 minutes (or another time nominated in the config) without having to navigate or press any buttons (these screens are left open for a long time in reality)

In this PR:
- implement autorefresh for DataFetchingTable (adjustable in config)
- partial refactor of DataFetchingTable to separate tangled functionality a bit, we decided actually breaking it up into separate components was out of scope though
- McLean reviewed originally & then paired on the refactoring, doesn't need a detailed review

Auto-refresh behaviour (screenshots and in depth behaviour added to linear ticket)
- **When on page 1 sorted reverse chronologically**, the page will live update when the autorefresh triggers. New rows will show at the top highlighted in green until the user does an action click (clicking into request, navigating, changing sort, searching).
- **When past page 1 and/or sorted anything other than reverse chronologically** when an autorefresh triggers, it should show a notification with the number of new rows added. When the refresh happens in this state the data won't update until interacted with an action click. This notification should stay visible until the user returns the table to page 1 sorted reverse chronologically to view the new rows or clears the notification manually.

### Checklist

- [x] Code is finished
- [x] UI Screenshots added to the Linear issue
- [x] Testing notes added to the Linear issue

_Upon merging:_

- [x] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [x] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [x] any config/settings changes and manual deployment steps

2023-08-17 04:50 UTC, mcccclean requested changes
Change notes from pairing session (more detailed changes to DataFetchingTable pending):

2023-09-04 13:15 UTC, renatokoyama approved these changes

2023-09-14 21:24 UTC, renatokoyama approved these changes

2023-09-15 00:57 UTC, mcccclean approved these changes
LGTM! The color syntax thing is still a todo but I think it's highly unlikely that it'd actually turn into an issue and I don't think it warrants delaying merging this PR.

2023-09-15 01:01 UTC, anilvkaran approved these changes

2023-09-15 01:04 UTC, merged