EPI-546 read visualisation config from validation criteria for
beyondessential/tamanu pull request #4411
Opened 2023-07-14 08:04 UTC by biaoli0

### Changes

_Add a brief description of the changes in this PR to help give the reviewer context._

### Checklist

- [ ] Code is finished
- [ ] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

2023-07-17 04:02 UTC, mcccclean requested changes
Hey, I've left some fairly involved change requests on this one I'm sorry - I think everything here will work OK, but some of it's arranged in a way that I can see causing some maintenance headaches later. If you have any questions, need a hand with anything, or are worried that it won't doable in time please message me and I'll help out :pray:

2023-07-19 01:05 UTC, stretchkennedy approved these changes
Few nits and recommendations, but all McLean's comments are addressed and it overall looks good 👍 

One thing to note is that we should definitely write tests around it. Even if they don't make it into this release it'd be comforting to have some working tests on main for the validation logic 
 before it's deployed, just to be 100% sure

2023-07-19 01:17 UTC, mcccclean requested changes
Few more changes to suggest :pray: 

(oop didn't see you'd reviewed it already @stretchkennedy, thanks for that! :pray:)

2023-07-20 05:09 UTC, mcccclean approved these changes

2023-07-20 06:44 UTC, merged