EPI-578 Include encounter reference in servicerequest
beyondessential/tamanu pull request #4475
Opened 2023-07-27 23:19 UTC by biaoli0

### Changes
~Add encounter reference in ServiceRequest response for both lab request and imaging request, similar to patient as 'subject'. Note: Imaging request already have the encounter reference.~
1. Follow upstream:// pattern for encounter
2. Add SQL procedure service_requests_resolve_upstream_encounter()
3. New unit test

### Manual changes:
1. Question on migration to add SQL procedure service_requests_resolve_upstream_encounter()? (cannot add locally, fatal error: SequelizeDatabaseError: syntax error at or near "UPDATE")
   - Have tried some old query for procedure, it throws the same error, not sure why... So for my local I just manually run the query. Trying to figure out why.
3. Refresh all service requests for updating `type` from `encounter` to `upstream://encounter`, also it will add `encounter.reference=[public.encounter.id]` in encounter column
``` 
node dist/app.bundle.js fhir --refresh ServiceRequest
```
4. Run the above command again to overwrite `encounter.reference` by `fhir.encounter.id`

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

2023-07-28 00:15 UTC, NavarroEmilioLuis requested changes
OK so the change was simple but not that simple! 😅 I believe this will not work (could always be wrong) but:

2023-08-01 03:50 UTC, passcod reviewed
Generally LGTM, a few question

2023-08-01 03:58 UTC, passcod approved these changes

2023-08-02 23:46 UTC, NavarroEmilioLuis approved these changes
Amazing work! Nice pickups! (happy to double stamp - thanks Felix for taking a look)

2023-08-09 22:11 UTC, merged