SAV-286: Add validation for records updated between push snapshot and pull
beyondessential/tamanu pull request #4599
Opened 2023-08-20 12:17 UTC by chris-bes

### Changes
- Add validation for records updated between push and pull

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

2023-08-21 07:26 UTC, mcccclean requested changes
Great stuff, just a couple tiny tweaks

2023-08-31 22:47 UTC, edmofro reviewed
Agree with McLean that this is super clear, nice work @chris-bes! Did you notice if there's much performance impact? Because it's a one time thing across an entire sync, I think it should be ok, but would be worth checking with a large sync use case 🙏

2023-09-10 23:29 UTC, mcccclean approved these changes

2023-09-15 00:47 UTC, anilvkaran approved these changes

2023-09-15 00:58 UTC, edmofro approved these changes

2023-09-15 01:01 UTC, merged