NASS-891: Translation backend setup
beyondessential/tamanu pull request #4801
Opened 2023-10-13 03:47 UTC by tcodling

### Changes

This card covers the foundations of the backend work for the desktop part of the translations project. For context the basic workflow for translations (as of right now) is going to be as follows

1. When arriving on the login screen you see a dropdown of possible languages fetched from `preLogin` endpoint
2. On login we use the selected language to fetch an object with all TranslatedStrings from the db for the selected language using the `:language` endpoint. This is stored in a to be created translation context
3. Each TranslatedText component will have a `stringId`. When the component renders, it should look into the translation context for the relevant translation for the defined `stringId` and displays as the string.

It includes: 
- TranslatedString model
- TranslatedString table migration
- Endpoint for fetching all language options for the login screen
  - Expected format: Select options format (array of objects with label/value)
- Endpoint for fetching all translations object for a language  (to be stored in translation context later)
  - Expected format:
```
{
   patientDetailsForm.address: "Address",
   patientDetailsForm.dateOfBirth: "DOB"
}
```

### Checklist

- [x] Code is finished
- [x] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

2023-10-17 09:07 UTC, passcod reviewed
generally looks good but many questions

2023-10-23 20:57 UTC, dannash100 reviewed
Just some ideas re tests in response to ur comment 🙏

2023-11-02 22:33 UTC, passcod requested changes

2023-11-05 20:14 UTC, passcod approved these changes

2023-11-05 20:26 UTC, merged