feat(reports): MDEV-194: adding new date ranges to report definition
beyondessential/tamanu pull request #5509
Opened 2024-03-14 21:11 UTC by renatokoyama

### Changes

Flynn:
- Added new previous 7 day range

Renato's:
Added 30 future days into report definition
https://linear.app/bes/issue/MDEV-194/new-future-30-days-default-date-range-for-db-report

### Checklist

- [ ] Code is finished
- [ ] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

- [x] **Deploy to Tamanu Internal**

2024-04-10 03:12 UTC, flynncs requested changes
few small questions regarding comments
is it possible to append `past` to the other date ranges? i.e. `30days` to `past30Days`? I think this would make it a bit clearer given there's now the option for a future date range

2024-04-12 00:29 UTC, chris-bes requested changes
LGTM! Just 1 minor request

2024-04-18 01:30 UTC, chris-bes approved these changes
LGTM!

2024-04-22 22:08 UTC, flynncs approved these changes

2024-05-30 02:30 UTC, merged