feat(settings): NASS-920: DB reader minimum
beyondessential/tamanu pull request #5573
Opened 2024-03-22 00:53 UTC by dannash100

### Changes
- bare minimum for model changes and migration for mobile
- settings package
- admin panel
- setup of settings reader for facility, central and web
- remove settings subcommand as discussed

No actual usages or breaking changes in this pr

- [x] **Deploy to Tamanu Internal** 

### Checklist

- [x] Code is finished
- [x] Tests are written
- [x] UI Screenshots added to the Linear issue
- [x] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

2024-04-08 01:04 UTC, passcod requested changes
One thing that's potentially missing is a way to clear the setting cache from outside the tamanu db code. Like if you want to force clear it for maintenance, what does that look like.

Otherwise two minor bits and lgtm.

2024-04-08 13:32 UTC, passcod requested changes

2024-04-08 21:34 UTC, passcod approved these changes

2024-04-08 21:56 UTC, edmofro approved these changes
Codeowner stamp for the sync section

2024-04-23 02:41 UTC, passcod approved these changes

2024-04-25 23:05 UTC, chris-bes approved these changes
Code owner stamp

2024-04-28 21:41 UTC, merged