feat(imports): NASS-1226: Scheduled vaccine import validation
beyondessential/tamanu pull request #5697
Opened 2024-04-16 03:51 UTC by flynncs

### Changes

Implemented further validation to the scheduled vaccine ref data import according to the following spec:

'We want to add validation to make sure that scheduled vaccines all have dose 1 either weeksFromBirth or blank, and doses beyond that have only weeksFromLastVaccine or blank.'

### Checklist

- [x] Code is finished
- [ ] Tests are written
- [ ] UI Screenshots added to the Linear issue
- [ ] Testing notes added to the Linear issue

_Upon merging:_

- [ ] Update the changelog (find it [here](https://github.com/beyondessential/tamanu/releases) in the appropriate _draft_ release)
  - [ ] with a ticket reference (e.g. `TAN-123: a one line description`, keep the lists sorted)
  - [ ] any config/settings changes and manual deployment steps
  - [ ] any db schema or other changes that could impact downstream data analysis
- [ ] Update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly) or [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q) as needed
- [ ] Update the [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c) as needed

### Deploys

- [x] **Deploy to Tamanu Internal**

2024-04-17 01:30 UTC, passcod requested changes
One lint that needs fixing and a wording suggestion, but lgtm otherwise

2024-04-17 21:34 UTC, dannash100 requested changes
Some ideas and questions!

2024-04-22 23:17 UTC, passcod approved these changes

2024-05-06 22:28 UTC, dannash100 approved these changes

2024-05-14 02:40 UTC, merged