feat(sync): SAV-650: Queue sync requests
beyondessential/tamanu pull request #5920
Opened 2024-05-26 08:50 UTC by chris-bes

### Changes
- Having facility running on multiple processes added a lot of complexity when dealing with sync. Hence, the solution is to add separate local server for sync only to allow having it running on 1 process (no cluster mode). 

### Deploys

- [x] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

2024-06-07 04:48 UTC, edmofro requested changes
Awesome work @chris-bes! This is actually super clean and I think breaking out sync into a micro-service encapsulates it a little better too

2024-06-12 21:51 UTC, edmofro requested changes
One more little tweak, then it's good to go

2024-06-20 23:35 UTC, edmofro approved these changes

2024-06-26 23:29 UTC, Harnesh787 approved these changes

2024-06-26 23:38 UTC, merged