repo(packageManager): SAV-644: Move to npm
beyondessential/tamanu pull request #5932
Opened 2024-05-28 02:33 UTC by NavarroEmilioLuis

### Changes

Okay so this seems to do the trick. Now: we have to merge and release to ensure it actually works completely. Another big gotcha is the way npm handles the command line flags, I tried to go with what I thought was most simple: everything explicitly, in about the same order (prefer `--workspace` and explicitly adding the separator `--` to each script)

### Deploys

- [x] **Deploy to Tamanu Internal**

2024-06-24 03:22 UTC, passcod requested changes
looks good in aggregate. a few wtfs

2024-10-24 08:27 UTC, passcod requested changes

2024-10-25 19:16 UTC, passcod approved these changes
one last optional thing but other lgtm

2024-10-31 23:22 UTC, edmofro approved these changes
stamp

2024-11-02 12:39 UTC, passcod approved these changes

2024-11-02 12:55 UTC, merged