feat(invoicing): EPI-831: Add config to show patient insurer fields in Cambodia
beyondessential/tamanu pull request #6142
Opened 2024-07-15 10:34 UTC by huytranbes

### Changes

Resolving issue stated in this comment: https://linear.app/bes/issue/EPI-831/capture-insurer-in-patient-details#comment-8489ffd6

### Deploys

- [ ] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

2024-07-16 20:38 UTC, tcodling requested changes
Nice job! Only thing is that you should add a default of `false` for this setting to the `config/default.json` in the central server package 🙏

2024-07-18 04:07 UTC, tcodling approved these changes
lgtm!

2024-07-18 04:08 UTC, tcodling approved these changes
lgtm! just need to sort out the determinism test. Just ask me or Khoi if you need help resolving this!

2024-07-18 04:21 UTC, Harnesh787 approved these changes

2024-07-18 04:23 UTC, merged