fix(sync): SAV-777: Handle server restarts during session initiation
beyondessential/tamanu pull request #6223
Opened 2024-07-30 04:58 UTC by edmofro

### Changes

Apply same pattern as restart handling during snapshots

### Deploys

- [ ] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

2024-07-30 05:16 UTC, rohan-bes requested changes
Great fix! 

How unit test-able do you think this is? Given it's a bug we caught in the wild it might be nice to have a test around it.

Ah sorry just saw your comment :joy: I'm feeling inclined so I'll give it a shot

2024-08-02 00:06 UTC, edmofro reviewed
Thank you so much! I've got one suggestion but it is very optional. I can't actually approve this as the author though

2024-08-26 07:26 UTC, rohan-bes approved these changes

2024-09-17 05:24 UTC, chris-bes approved these changes
code owner stamp

2024-09-17 06:35 UTC, merged