feat(tasking): EPI-943: Add new reference data type 'Designation'
beyondessential/tamanu pull request #6243
Opened 2024-08-05 07:43 UTC by huytranbes

### Changes

- Add new reference data type 'Designation'
- Add validation for designation name uniqueness

### Deploys

- [x] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

2024-08-08 01:44 UTC, chris-bes approved these changes
LGTM!

2024-08-08 04:42 UTC, chris-bes requested changes

2024-08-13 03:41 UTC, khoi-bes approved these changes
LGTM!

2024-08-13 05:27 UTC, chris-bes approved these changes
Always happy every time we avoid introducing more complexity!

2024-08-13 08:44 UTC, merged