feat(tasking): EPI-935: Build add task workflow
beyondessential/tamanu pull request #6378
Opened 2024-08-30 10:38 UTC by huytranbes

### Changes

Build add task workflow

### Deploys

- [ ] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

2024-09-05 21:52 UTC, dannash100 requested changes
Some ideas :)

2024-09-08 21:41 UTC, dannash100 approved these changes
Thank you great work. There is a lint issue but ill give tick

2024-09-09 03:54 UTC, namhoangbes requested changes

2024-09-11 07:13 UTC, namhoangbes approved these changes

2024-09-23 02:12 UTC, merged