fix(sync): SAV-831: Improve sync lookup performance when there is no new patients marked for sync
beyondessential/tamanu pull request #6506
Opened 2024-09-25 03:54 UTC by rohan-bes

### Changes

This pull request introduces a new utility function to simplify the generation of patient-related SQL where clauses and updates the `snapshotOutgoingChanges.js` file to use this function. The changes help to clean up the code and make it more maintainable.

### Codebase simplification:

* [`packages/central-server/app/sync/snapshotOutgoingChanges.js`](diffhunk://#diff-cfd648877afd967153e5754247d1866343ef6b08db97d7e1f038142aa7d31130R10): Added import for `getPatientLinkedModels` to use in the new utility function.
* [`packages/central-server/app/sync/snapshotOutgoingChanges.js`](diffhunk://#diff-cfd648877afd967153e5754247d1866343ef6b08db97d7e1f038142aa7d31130R186-R212): Introduced `getPatientRelatedWhereClause` function to generate SQL where clauses for patient-related records.
* [`packages/central-server/app/sync/snapshotOutgoingChanges.js`](diffhunk://#diff-cfd648877afd967153e5754247d1866343ef6b08db97d7e1f038142aa7d31130L233-R266): Replaced inline SQL where clause logic with calls to the new `getPatientRelatedWhereClause` function.

### Deploys

- [ ] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

2024-09-25 18:55 UTC, NavarroEmilioLuis requested changes
Here are a couple of suggestions, I think the most important one being the one you commented, we could benefit from rewriting it somehow

2024-09-26 06:57 UTC, edmofro reviewed
Our comments are mostly on semantics, just wanted to say overall this is a great find and improvement!

2024-09-27 01:16 UTC, edmofro approved these changes
lgtm!

2024-09-27 02:19 UTC, NavarroEmilioLuis approved these changes

2024-09-27 02:24 UTC, merged