fix(sync): SAV-837: Avoid repull pushed changes from the previous sync session when using sync lookup
beyondessential/tamanu pull request #6545
Opened 2024-10-03 23:55 UTC by chris-bes

### Changes
- Avoid repull pushed changes from the previous sync session when using sync lookup

### Deploys

- [x] **Deploy to Tamanu Internal** 

### Remember to...

- ...write or update tests
- ...add UI screenshots and **testing notes** to the Linear issue
- ...add any **manual upgrade steps** to the Linear issue
- ...update the [config reference](https://beyond-essential.slab.com/posts/reference-config-file-0c70ukly), [settings reference](https://beyond-essential.slab.com/posts/reference-settings-0blw1x2q), or any [relevant runbook(s)](https://beyond-essential.slab.com/topics/runbooks-bs04ml6c)
- ...call out additions or changes to **config files** for the deployment team to take note of

2024-10-04 00:15 UTC, edmofro requested changes
Amazing, this is actually relatively light touch compared to what I expected - very nice work!!

2024-10-07 02:48 UTC, edmofro reviewed
Latest changes lgtm, thanks for adding the test!

2024-10-09 07:09 UTC, edmofro approved these changes

2024-10-14 02:06 UTC, Harnesh787 approved these changes

2024-10-14 02:07 UTC, merged