feat(db): EPI-1022: Create db change responsiveness via pub/sub
beyondessential/tamanu pull request #6600
Opened 2024-10-22 01:39 UTC by namhoangbes

### Changes

- Implementing db notify

### Deploys

- [ ] **Deploy to Tamanu Internal**

2024-10-22 21:17 UTC, dannash100 reviewed
Will have a closer look when online thursday 🙏 Great cleanups and consolidations to what I added during upcomingVaccinations stuff 😆

2024-11-07 18:42 UTC, dannash100 requested changes
@namhoangbes needs to be rebased or merged to remove diff from main if possible.

2024-11-14 03:00 UTC, dannash100 approved these changes
Looks great!
It will be a very cool feature going forwards

2024-12-20 02:29 UTC, chris-bes approved these changes

2024-12-24 03:33 UTC, merged